name:                hanabi
version:             0.1.0.0
github:              "xaviershay/hanabi"
license:             BSD3
author:              "Xavier Shay"
maintainer:          "contact@xaviershay.com"
copyright:           "2018 Xavier Shay"

# extra-source-files:
# - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Hanabi clone

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - servant-server
    - stm
    - transformers
    - text
    - unordered-containers
    - containers
    - hashable
    - lens
    - random
    - wai-cors
    - wai-extra
    - parsec
    - pretty-show
    - time
    - freer-simple
    - random-shuffle

executables:
  hanabi-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hanabi
    - servant-server
    - wai
    - warp
    - pretty-show
    - text
    - containers

tests:
  hanabi-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wunused-imports
    dependencies:
    - hanabi
    - aeson
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
    - random
    - random-shuffle
    - lens
    - containers
    - unordered-containers
    - text
    - hashable
